less artsy rewrite of app_epath

diff --git a/rel/files/stanchion-debug b/rel/files/stanchion-debug
--- a/rel/files/stanchion-debug
+++ b/rel/files/stanchion-debug
@@ -23,6 +23,12 @@
 ##
 ## -------------------------------------------------------------------
 
+set +e
+# this is to revert the effect of `set -e`, set by relx-generated code
+# when we are invoked via `riak-cs debug` (otherwise, non-zero exits,
+# which occur normally, will silently cause riak-cs-debug to
+# terminate)
+
 # /bin/sh on Solaris is not a POSIX compatible shell, but /usr/bin/ksh is.
 if [ `uname -s` = 'SunOS' -a "${POSIX_SHELL}" != "true" ]; then
     POSIX_SHELL="true"
@@ -139,8 +145,8 @@ is_relative() {
         return 1
     fi
 }
-STANCHION_PATH="${STANCHION_PATH:-$(cd $(dirname "$0")/.. && pwd -P)}"
 PLATFORM_BASE_DIR={{platform_base_dir}}
+PLATFORM_BASE_DIR=${PLATFORM_BASE_DIR:-$(cd $(dirname "$0")/.. && pwd -P)}
 stanchion_base_dir=$PLATFORM_BASE_DIR
 if is_relative "{{platform_bin_dir}}"; then
     stanchion_bin_dir="$PLATFORM_BASE_DIR/{{platform_bin_dir}}"
@@ -256,6 +262,8 @@ while [ -n "$1" ]; do
     shift
 done
 
+cd $PLATFORM_BASE_DIR
+
 ###
 ### Finish setting up variables and overrides
 ###
@@ -278,21 +286,7 @@ if [ 0 -ne $(( $get_cfgs + $get_logs + $get_riakcmds + $get_extracmds )) ]; then
     # Information specific to Riak requested. Need app_epath.sh and must have
     # valid base and etc paths defined.
 
-    # app_epath.sh provides make_app_epaths and epath functions.
-    # Allow overriding with APP_EPATH
-    if [ -n "$APP_EPATH" ]; then
-        epath_file="$APP_EPATH"
-    else
-        epath_file="${stanchion_lib_dir}/app_epath.sh"
-    fi
-
-    if [ ! -f "$epath_file" ]; then
-        echoerr "Required file app_epath.sh not found. Expected here:"
-        echoerr "$epath_file"
-        echoerr "See 'stanchion-debug -h' and manpage for help."
-        exit 1
-    fi
-    . "$epath_file"
+    . $stanchion_lib_dir/lib.sh
 
     # Allow overriding stanchion_base_dir and stanchion_etc_dir from the environment
     if [ -n "$stanchion_base_dir" ]; then
@@ -488,7 +482,7 @@ if [ 1 -eq $get_syscmds ]; then
 fi
 
 ###
-### Gather Riak commands and info
+### Gather Stanchion commands and info
 ###
 
 if [ 1 -eq $get_riakcmds ]; then
@@ -497,13 +491,12 @@ if [ 1 -eq $get_riakcmds ]; then
 
     dump stanchion_ping "$stanchion_bin_dir"/stanchion ping
     dump stanchion_version "$stanchion_bin_dir"/stanchion-admin version
-    dump stanchion_config_effective "$stanchion_bin_dir"/stanchion config effective
     dump stanchion_getpid "$stanchion_bin_dir"/stanchion pid
     dump stanchion_admin_status "$stanchion_bin_dir"/stanchion-admin status
 fi
 
 ###
-### Gather Riak logs
+### Gather Stanchion logs
 ###
 
 if [ 1 -eq $get_logs ]; then
